- name: remote-bash
  # You may pin to the exact commit or the version.
  # uses: shinhwagk/remote-bash@c03b11eac4cceccef56a495916311d9d49875f4d
  uses: shinhwagk/remote-bash@0.0.1
  - name: terraform-plan-storage
  # You may pin to the exact commit or the version.
  # uses: cloudposse/github-action-terraform-plan-storage@68f48c4cab5d6163d634df904ef654b7e69c4e1f
  uses: cloudposse/github-action-terraform-plan-storage@1.6.2
  with:
    # which action to perform. Valid values are: 'storePlan', 'getPlan', 'taintPlan'
    action: # default is storePlan
    # path to the Terraform plan file. Required for 'storePlan' and 'getPlan' actions
    planPath: # optional
    # the name of the dynamodb table to store metadata
    tableName: # default is terraform-plan-storage
    # the name of the S3 bucket to store the plan file
    bucketName: # default is terraform-plan-storage
    # the name of the component corresponding to the plan file
    component: # optional
    # the name of the stack corresponding to the plan file
    stack: # optional
    - name: nodenv/setup-nodenv
  # You may pin to the exact commit or the version.
  # uses: nodenv/actions-setup-nodenv@6faff6196d33cbbcd308c6b4af7cda5f4fd834f5
  uses: nodenv/actions-setup-nodenv@v2.0.4
  with:
    # The version of nodenv to install
    nodenv-version: # optional, default is 1.3.1
